### PR TITLE
Optional Mime type for moveToSharedStorage

### LINKED ISSUE #24: Incorrect MIME type when moving files to shared storage
Hi, 

I've noticed that sometimes the `getMimeType` function in Android returns an incorrect MIME type, which can cause issues when trying to insert media files into a specified destination.  I've modified the code to correctly get the MIME type from the file name, and added an optional mimeType parameter that can be set when moving files to ensure that the correct mime type is used even if not determined easily.

### PR DESCRIPTION
**Pull request by 781flyingdutchman**
@rebaz94 thanks for adding this!  Fixes #24 
I'll run some tests and merge into the main branch. Thanks again!

### CODE REVIEW

**Comment by 781flyingdutchman** [comment]
@rebaz94 I noticed that when overriding the mimeType Android may change the filename. For example, I added a test that tries to move the google.html file to the .images shared storage, and it changes the name to /storage/emulated/0/Pictures/google.html.jpg

I don't think this is a problem, just wanted to make sure that's OK also from your perspective. The plugin accurately returns the path to the destination, so everything should work as intended.

**Comment by 781flyingdutchman** [comment]
@rebaz94 I pushed the proposed final version 5.4.3 to the dev branch of my repo. I'll publish in a few hours unless I hear concerns from you.

**Comment by rebaz94** [comment]
> @rebaz94 I noticed that when overriding the mimeType Android may change the filename. For example, I added a test that tries to move the google.html file to the .images shared storage, and it changes the name to /storage/emulated/0/Pictures/google.html.jpg
> 
> I don't think this is a problem, just wanted to make sure that's OK also from your perspective. The plugin accurately returns the path to the destination, so everything should work as intended.

@781flyingdutchman Thank you for informing me. I didn't realize that this was possible. It's good to know that overriding the mimeType works, although we should be cautious and only do so for specific types. Otherwise, it throw an "Unsupported" error. Thanks again for bringing this up.

**Comment by rebaz94** [comment]
For download folder, maybe overriding work for any mime type but for other specific folders, only work for some of them. Like changing mp3 to m4a but not for mpeg-m1.

**Pull request merged**
